
# menu:
#   main:
#     - identifier: abteilungen
#       name: Abteilungen
#       url: /abteilungen/
#       weight: 20
#     - identifier: aalbachtaler
#       parent: abteilungen
#       name: Die Aalbachtaler
#       url: /abteilungen/die_aalbachtaler
#       weight: 10
#
baseURL = 'https://aalbachtaler-musikverein.de/'
languageCode = 'de'
title = 'Aalbachtaler-Musikverein e.V. - the home of real music'
theme = 'ananke'

# menu = ['main', 'footer']

[params]
  text_color = ""
  favicon = ""
  site_logo = ""
  description = ""
  background_color_class = "bg-green"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[taxonomies]
  category = 'categories'
  tag = 'tags'